### PR TITLE
Pass original URL to curl_modify_url() to keep original encoding

### LINKED ISSUE #786: htt2 >= 1.2.0 replaces '%2f' with '/' in the URL
Which is probably something that it should not do?

So e.g. this does not work any more:
```r
❯ gh::gh("/orgs/r-hub/packages/container/containers%2fatlas/versions", per_page = 5)
Error in `gh::gh()`:
! GitHub API error (404): Not Found
✖ URL not found: <https://api.github.com/orgs/r-hub/packages/container/containers/atlas/versions?per_page=5>
ℹ Read more at <https://docs.github.com/rest>
Run `rlang::last_trace()` to see where the error occurred.
```

```r
❯ rlang::last_trace()
<error/github_error>
Error in `gh::gh()`:
! GitHub API error (404): Not Found
✖ URL not found: <https://api.github.com/orgs/r-hub/packages/container/containers/atlas/versions?per_page=5>
ℹ Read more at <https://docs.github.com/rest>
---
Backtrace:
    ▆
 1. └─gh::gh(...)
Run rlang::last_trace(drop = FALSE) to see 4 hidden frames.
```

### PR DESCRIPTION
**Pull request by jeroen**
This changes the logic of `modify_url()` to start with the original URL and modify it, rather than build it from scratch from the list of its components. 

This should prevent normalisation of components of the URL that we do not modify, in particular the escaped slash.

Fixes #786

### CODE REVIEW

File: tests/testthat/test-url.R [hunk 1]
```diff
@@ -127,6 +127,12 @@ test_that("path always starts with /", {
   expect_equal(url_modify("https://x.com/abc", path = NULL), "https://x.com/")
 })
 
+test_that("escaped slashes are retained", {
```
Comment (hadley) [inline tests/testthat/test-url.R:130]:
```suggestion
test_that("only modifies specified components", {
```

**Review by hadley — APPROVED** [review]
LGTM. Want to add a news bullet and then I'll resubmit to CRAN in a couple of days?

**Comment by jeroen** [comment]
> LGTM. Want to add a news bullet and then I'll resubmit to CRAN in a couple of days?

I'm not sure if it's urgent to release this. It's a really unusual case, I doubt anyone else is affected.

**Comment by hadley** [comment]
Ok, I'll just do a release when it feels right then 😄
